// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuArrowUpRight, LuBookOpen, LuChevronRight, LuContact, LuGlobe, LuImage, LuMail, LuPhone, LuSettings, LuTrendingUp, LuUsers } from 'react-icons/lu';
import { FaArrowRight, FaArrowsUpDownLeftRight, FaBullseye, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaLayerGroup, FaLifeRing, FaLink, FaMoon, FaPalette, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaSun, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { PiBrain, PiCode, PiGauge, PiMagnifyingGlass, PiPenNib, PiShoppingCart } from 'react-icons/pi';
import { SiFacebook, SiGithub, SiLinkedin, SiX } from 'react-icons/si';

export const iconMap = {
  'fa6:arrow-right': FaArrowRight,
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bullseye': FaBullseye,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:moon': FaMoon,
  'fa6:palette': FaPalette,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:sun': FaSun,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'lu:arrow-right': LuArrowRight,
  'lu:arrow-up-right': LuArrowUpRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:mail': LuMail,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'lu:trending-up': LuTrendingUp,
  'lu:users': LuUsers,
  'pi:brain': PiBrain,
  'pi:code': PiCode,
  'pi:gauge': PiGauge,
  'pi:magnifying-glass': PiMagnifyingGlass,
  'pi:pen-nib': PiPenNib,
  'pi:shopping-cart': PiShoppingCart,
  'si:facebook': SiFacebook,
  'si:github': SiGithub,
  'si:linkedin': SiLinkedin,
  'si:x': SiX,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
